contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact' # Adicionar o nome do app

urlpatterns = [
    path('', views.index, name='index'), # adicionar a view na url
    path('search/', views.search, name='search'),
    
    # Contact (CRUD)
    path('contato/<int:contact_id>/detalhes/', views.contact, name='contact'),
    path('contato/<int:contact_id>/atualizar/', views.update, name='update'),
    path('contato/<int:contact_id>/delete/', views.delete, name='delete'),
    path('contato/create/', views.create, name='create'),
    
    # USER 
    path('user/create/', views.register, name='register'),
    path('user/login/', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    path('user/update/', views.user_update, name='user_update'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('contact.urls')), # Incluir urls do app
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    name = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.name}'
    

# Qualquer coisa que mudar no model, executar o comando: python manage.py makemigrations
class Contact(models.Model):
    first_name = models.CharField(max_length=50, verbose_name="NOME")
    last_name = models.CharField(max_length=50, blank=True, verbose_name="SOBRENOME") # pode ficar em branco
    phone = models.CharField(max_length=50, verbose_name="TELEFONE")
    email = models.EmailField(max_length=254 , verbose_name="E-MAIL")
    created_date = models.DateTimeField(default=timezone.now())
    description = models.TextField(blank=True, verbose_name="DESCRIÇÃO")
    
    show = models.BooleanField(default=True) # Se precisa mostrar
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m/')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True,)

    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True, null=True,
    )

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

contact/forms.py
from django import forms
from django.core.exceptions import ValidationError
from . import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
# from contact.forms import ContactForm

from django.contrib.auth import password_validation


class ContactForm(forms.ModelForm):
    picture = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'accept': 'image/*',
            }
        ), required=False
    )

    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                 'class':'classe-a',
                 'placeholder':'INFORME SEU NOME',
            }
        ),
        label='PRIMEIRO NOME',
        # help_text='TEXTO DE AJUDA'
    ) 

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['first_name'].widget.attrs.update({
    #          'class':'classe-a',
    #          'placeholder':'INFORME SEU NOME',
    #     })

    class Meta:
        model = models.Contact
        fields = (
            'first_name','last_name','email','phone', 
            'email', 'description', 'category', 'picture',
                  )        
        # widgets = {
        #     'first_name': forms.TextInput(
        #         attrs={
        #             'class':'classe-a',
        #             'placeholder':'INFORME SEU NOME',
        #         }
        #     ),
        #     'email': forms.TextInput(
        #         attrs={
        #             'class':'classe-a',
        #             'placeholder':'INFORME SEU EMAIL',
        #         }
        #     )
        # }

    def clean(self):
        cleaned_data = self.cleaned_data
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if first_name == last_name:
            msg = ValidationError(
                    'Primeiro nome não pode ser igual ao sobrenome',
                    code='invalid'
                )
                
            self.add_error(
                'last_name', msg
                )
            

        # self.add_error(
        #     'first_name',
        #     ValidationError(
        #         'Mensagem de Erro',
        #         code='invalid'
        #     )
        # )

        
        # self.add_error(
        #     None,
        #     ValidationError(
        #         'Mensagem de error: ',
        #         code='invalid'
        #     )
        # )

        return super().clean()
    
    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        
        if first_name == 'ABC':
            self.add_error(
                'first_name',
                ValidationError(
                    'Não digite ABC neste campo',
                    code='invalid'
                )
            )
        
        return first_name

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(
        required=True,
        min_length=3, 
        widget=forms.TextInput(
            attrs={
                 'class':'classe-a',
                 'placeholder':'INFORME SEU NOME',
            }
        ),
        label='PRIMEIRO NOME',
    )
    last_name = forms.CharField(
        required=True,
        min_length=3, 
        widget=forms.TextInput(
            attrs={
                 'class':'classe-a',
                 'placeholder':'INFORME SEU SOBRENOME',
            }
        ),
        label='SOBRENOME',        
    )
    
    # email = forms.EmailField(
    #     required=True,
    # )

    class Meta:
        model = User
        fields = (
            'first_name','last_name','email',
            'username','password1','password2',
        )

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError('Já existe este e-mail', code='invalid')

            )
        return email
    

class RegisterUpdateForm(forms.ModelForm):
    first_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.',
        error_messages={
            'min-length': 'Por favor, adicione mais 2 letras'
        }
    )

    last_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.'
    )

    password1 = forms.CharField(
        label= 'Senha',
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete':'nova-senha'}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
    )

    password2 = forms.CharField(
        label= 'Repetir Senha',
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete':'nova-senha'}),
        help_text='Digite a senha novamente',
        required=False,
    )

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username', 
        )


    def save(self, commit=True):
        cleaned_data = self.cleaned_data
        user = super().save(commit=False)

        password = cleaned_data.get('password1')

        if password:
            user.set_password(password)

        if commit:
            user.save()

        return user       

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 or password2:
            if password1 != password2:
                self.add_error(
                    'password2',
                    ValidationError('Senhas diferentes')
                )

        return super().clean()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        current_email = self.instance.email 

        if current_email != email:
            if User.objects.filter(email=email).exists():
                self.add_error(
                    'email',
                    ValidationError('Já existe este email', code='invalid')

                )

        return email
    
    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if password1:
           try:
               password_validation.validate_password(password1)
           except ValidationError as errors:
               self.add_error(
                   'password1',
                   ValidationError(errors),
               )
               
               

        return password1

contact/views/contact_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from contact.forms import ContactForm  
from django.urls import reverse
from contact.models import Contact
# Create your views here.

from django.contrib.auth.decorators import login_required

@login_required(login_url='contact:login')
def create(request):
    form_action = reverse('contact:create')
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)
        # print(request.POST.get('first_name'))           
        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            contact = form.save(commit=False) # Salvar na Base de dados || Commit == False não salva no BD ainda
            contact.owner = request.user # Inserir ID no contato
            contact.save() # Agora salva
            return redirect('contact:update', contact_id=contact.id)

        return render(request, 
                    'contact/create.html',
                    context,
                    )
    
    context = {
        'form': ContactForm(),
        'form_action': form_action,
    }

    return render(request, 
                'contact/create.html',
                context,
                )

@login_required(login_url='contact:login')
def update(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, show=True, owner=request.user)
    form_action = reverse('contact:update', args=(contact_id,))
   
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=contact)
        # print(request.POST.get('first_name'))           
        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            contact = form.save() # Salvar na Base de dados
            return redirect('contact:update', contact_id=contact.id)

        return render(request, 
                    'contact/create.html',
                    context,
                    )
    
    context = {
        'form': ContactForm(instance=contact),
        'form_action': form_action,
    }

    return render(request, 
                'contact/create.html',
                context,
                )

@login_required(login_url='contact:login')
def delete(request, contact_id):

    contact = get_object_or_404(Contact, pk=contact_id, show=True, owner=request.user)
    
    confirmation = request.POST.get('confirmation','no')
    if confirmation  == 'yes':
        contact.delete()
        return redirect('contact:index')

    return render(request,
                'contact/contact.html',
                {
                    'contact':contact,
                    'confirmation':confirmation
                }                  
                  )

contact/views/contact_views.py
from django.shortcuts import render, get_object_or_404, redirect
from contact.models import Contact
from django.db.models import Q

from django.core.paginator import Paginator
# Create your views here.

def index(request):
    contacts = Contact.objects.filter(show=True).order_by('-id')
    
    paginator = Paginator(contacts,10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'CONTATOS'
    }
    return render(request, 
                'contact/index.html',
                context,
                )


def search(request):
    search_value = request.GET.get('q','').strip()
    
    if search_value == '':
        return redirect('contact:index')
    
    contacts = Contact.objects \
    .filter(show=True) \
    .filter(Q(first_name__icontains=search_value) |
            Q(last_name__icontains=search_value)  |
            Q(phone__icontains=search_value)  |
            Q(id__icontains=search_value)  |
            Q(email__icontains=search_value)  
            ) \
    .order_by('-id')
    
    paginator = Paginator(contacts,10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    
    context = {
       'page_obj': page_obj,
       'site_title': 'Search',
       'search_value': search_value
    }
    return render(request, 
                'contact/index.html',
                context,
                )



def contact(request, contact_id):
    # single_contact = Contact.objects.filter(pk=contact_id).last()
    single_contact = get_object_or_404(Contact,pk=contact_id,show=True)

    contact_name = f'{single_contact.first_name} {single_contact.last_name}'
    context = {
        'contact': single_contact,
        'site_title': contact_name, 
    }
    return render(request, 
                'contact/contact.html',
                context,
                )

contact/views/user_forms.py
from django.shortcuts import render, redirect
from contact.forms import RegisterForm, RegisterUpdateForm
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm


def register(request):

    form = RegisterForm() 

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Usuário Registrado com Sucesso!')
            
            return redirect('contact:index')


    return render(request, 'contact/register.html',
                  {
                      'form': form
                  })

def login_view(request):
    form = AuthenticationForm(request)

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            messages.success(request, 'LOGADO COM SUCESSO')
            return redirect('contact:index')
        messages.error(request, 'LOGIN INVALIDO')

    return render(request, 'contact/login.html',
                  {
                      'form': form
                  }
                  )

@login_required(login_url='contact:login') # Só acessa essa função se estiver logado
def user_update(request):
    
    form = RegisterUpdateForm(instance=request.user)

    if request.method != 'POST':
        return render(
                request,
                'contact/user_update.html',
                {
                    'form':form
                }
            )
    form = RegisterUpdateForm(data=request.POST, instance=request.user)
    if not form.is_valid():
        return render(
            request,
           'contact/user_update.html',
                {
                    'form':form
                }
            )        
    form.save()
    return redirect('contact:user_update')
    
@login_required(login_url='contact:login')
def logout_view(request):
    auth.logout(request)
    return redirect('contact:login')

contact/templates/contact/contact.html
{% extends "global/base.html" %}

{% block content %}
<div class="single-contact">
    <h1 class="single-contact-name">
        {{ contact.first_name}} {{ contact.last_name}}
    </h1>

    <p><b>ID: </b>{{ contact.id }}</p>
    <p><b>E-MAIL: </b>{{ contact.email }}</p>
    <p><b>PHONE: </b>{{ contact.phone }}</p>
    <p><b>CREATED DATE: </b>{{ contact.created_date }}</p>
    <p><b>DESCRIPTION: </b>{{ contact.description }}</p>
    <p><b>CATEGORY: </b>{{ contact.category.name }}</p>

    {% if contact.picture %}
    <p>
        <img src=" {{ contact.picture.url }} " alt="{{ contact.first_name }} {{ contact.last_name }}">
    </p>
    {% endif %}
    {% comment %} VERIFICAR SE O CONTATO É PERTENCENTE AO LOGADO {% endcomment %}
    {% if user == contact.owner %}
    <div class="contacts-links">
        <a class="btn btn-link" href="{% url 'contact:update' contact.id %}">ATUALIZAR INFORMAÇÕES</a>
        
        <form method="POST" action="{% url 'contact:delete' contact.id %}">
          {% csrf_token %}
            {% if confirmation == 'no' %}
            <input type="hidden" name="confirmation" value="yes">
            <button style="background: tomato;" class="btn btn-link btn-delete" type="submit">CONFIRMAR?</button>
            {% else %}
            <button style="background: tomato;" class="btn btn-link btn-delete" type="submit">DELETAR</button>
            {% endif %}

        </form>
        
    </div>
    {% endif %}
</div>
{% endblock content %}

contact/templates/contact/create.html
{% extends "global/base.html" %}

{% block content %}

<div class="form-wrapper">
    <h1>CRIAR CONTATO</h1>
    <form action="{{ form_action }}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-content">
            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                
                {% if field.errors %}
                {% comment %} <div class="message error"> {% endcomment %}
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                {% comment %} </div> {% endcomment %}
                {% endif %}
                
                {% if field.help_text %}
                    <small>{{ field.help_text }}</small>
                {% endif %}
            </div>
                {% if field.name == 'picture' and field.value.url %}
                <div class="form-group">
                <img style='max-width:25%' src='{{ field.value.url }}' alt='' >
                </div>
                {% endif %}

           
            {% endfor %}
        

        {% if form.non_field_errors %}
        <div class="form-content">
            <div class="form-group">
                <div class="message error">
                    {% for error in form.non_field_errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}

        <div class="form-content">
            <div class="form-group">
                <button class="btn" type="submit">CADASTRAR</button>
            </div>
        </div>

    </form>
</div>

{% endblock content %}

contact/templates/contact/index.html
{% extends "global/base.html" %}

{% block content %}

{% if page_obj %}

    
<div class="responsive-table">
    <table class="contacts-table">
        <caption class="table-caption">
            Contacts
        </caption>
        <thead>
            <tr class="table-row table-row-header">
                <th class="table-header">ID</th>
                <th class="table-header">FIRST NAME</th>
                <th class="table-header">LAST NAME</th>
                <th class="table-header">PHONE</th>
                <th class="table-header">E-MAIL</th>
            </tr>
        </thead>
        <tbody>

            {% for contact in page_obj %}
            
            <tr class="table-row">
                <td class="table-cel"> 
                <a  class="table-link" href="{% url 'contact:contact' contact.id %}">
                    {{ contact.id }}
                </a>
                </td>
                <td class="table-cel">
                    {{ contact.first_name }}
                </td>
                <td class="table-cel">
                    {{ contact.last_name }}
                </td>
                <td class="table-cel">
                    {{ contact.phone }}
                </td>
                <td class="table-cel">
                    {{ contact.email }}
                </td>

            </tr>

            {% endfor %}

        </tbody>
    </table>
</div>

{% else %}

    <div class="single-contact">
        <h1 class="single-contact-name">
            NENHUM CONTATO ENCONTRADO!
        </h1>

    </div>
   
{% endif %}
{% endblock content %}

contact/templates/contact/login.html
{% extends "global/base.html" %}

{% block content %}

<div class="form-wrapper">
    <h1>LOGIN</h1>

    {% if user.is_authenticated %}
    <p> Você fez login como {{ user.username }}.
    Clique <a href="{% url "contact:logout" %}"> aqui</a> para sair.    
    </p>
    {% else %}
    
        {% include "contact/partials/_user-form.html" %}
    {% endif %}
        
</div>

{% endblock content %}

contact/templates/contact/register.html
{% extends "global/base.html" %}

{% block content %}

<div class="form-wrapper">
    <h1>REGISTER</h1>
    <form action="{{ form_action }}" method="POST">
        {% csrf_token %}

        <div class="form-content">
            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                
                {% if field.errors %}
                {% comment %} <div class="message error"> {% endcomment %}
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                {% comment %} </div> {% endcomment %}
                {% endif %}
                
                {% if field.help_text %}
                    <small>{{ field.help_text }}</small>
                {% endif %}

       
            {% endfor %}
        

        {% if form.non_field_errors %}
        <div class="form-content">
            <div class="form-group">
                <div class="message error">
                    {% for error in form.non_field_errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}

        <div class="form-content">
            <div class="form-group">
                <button class="btn" type="submit">CADASTRAR</button>
            </div>
        </div>

    </form>
</div>

{% endblock content %}

contact/templates/contact/user_update.html
{% extends "global/base.html" %}

{% block content %}

<div class="form-wrapper">
    <h1>Atualizando Usuário</h1>
    
    {% include "contact/partials/_user-form.html" %}
</div>

{% endblock content %}